package com.api.parkingcontrol.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "TB_PARKING_SPOT")
@AllArgsConstructor
@Getter @Setter @ToString
@EqualsAndHashCode
@ApiModel(value = "ParkingSpot",description = "Entity to represent a Parking Spot in a Condominium")
public class ParkingSpot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("Autogenerated Primary key of type Long")
    private Long id;

    @Column(nullable = false,unique = true)
    @ApiModelProperty("Unique attribute")
    private String parkingSpotNumber;

    //---
    @Column(nullable = false,unique = true)
    @ApiModelProperty("Unique attribute")
    private String licensePlateCar;

    @Column(nullable = false)
    private String brandCar;

    @Column(nullable = false)
    private String modelCar;

    @Column(nullable = false)
    private String colorCar;
    //--

    @Column(nullable = false)
    @ApiModelProperty("Attribute of type LocalDateTime")
    private LocalDateTime registrationDate;

    @Column(nullable = false)
    private String responsibleName;

    @Column(nullable = false)
    private String block;

    @Column(nullable = false)
    @ApiModelProperty(value= "Unique per block")
    private String apartment;


    public ParkingSpot(){
    }

}
